= specifications-ITS-JSON

JSON schemas for use with openEHR systems and tools. See https://specifications.openehr.org/release_baseline[release baseline] of current specifications.

Schema format is based on https://json-schema.org/specification.html[draft-07 of JSON-Schema specifications].

== Releases and IM Versions

NOTE: These schemas are in *DEVELOPMENT* state and subject to change.

The repository is structured as follows:

----
/examples                # JSON examples
/components
    /AM                  # schemas for AM component
        /Release-1.4     # schemas for Release-1.4 of AM
        /Release-2.1.0   # schemas for Release-2.1.0 of AM
        /Release-2.2.0   # schemas for Release-2.2.0 of AM
    /BASE                # schemas for BASE component
        /Release-1.0.3   # schemas for Release-1.0.3 of BASE
        /Release-1.1.0   # schemas for Release-1.1.0 of BASE
        /Release-1.2.0   # schemas for Release-1.2.0 of BASE
    /RM                  # schemas for RM component
        /Release-1.0.3   # schemas for Release-1.0.3 of RM
        /Release-1.0.4   # schemas for Release-1.0.4 of RM
        /Release-1.1.0   # schemas for Release-1.1.0 of RM
----

== Additional JSON-Schema keywords

Schemas are organized in directories considering openEHR components (e.g. `AM`, `RM`, etc.), release name and UML package (e.g. `/components/RM/Release-1.1.0/Data_Structures`). Each directory contains several json schema files, as follows:

- one file containing types of that package named as `all.json`
- one file containing types of that package with extended details named as `all-detailed.json`
- several files with standard json-schema properties (keywords) named as `[type].json`
- several files with extra json-schema keywords containing details extracted from openEHR UML, named as `[type]-detailed.json`

Keywords that are used to support openEHR metadata are: `$abstract`, `$inherits`, `$children`, `$functions`, `$invariants`, `$version` and `$component`. They don't have to be supported by JSON-Schema validators, their purpose is only informational and might be useful for code-generation tools.

== Known issues

The followings are some known issues of openEHR JSON-Schema. These will be addressed in the near future and will cause the schemas to be changed before it reaches maturity.

=== General issues

Detailed schemas are very big, containing a lot of information which proved slow down parsers. There are alsoo too many files and no root-node schema file to be used for a direct validation of specific `COMPOSITION` (as an example).

Schemas are generated (close-source code) from openEHR UML files. There are however plans to publish a new UML extractor.

=== Polymorphism, discriminator and validation

In practice the current schemas cannot be used for validation, because it does not implement the openEHR polymorphism including the `_type` column to discriminate types. As an example, if validations encounters a `CLUSTER` in a place where the model says `ITEM`, the items attribute of the cluster plus any of its content will not be checked at all.

A longer discussion about this subject can be found at https://discourse.openehr.org/[openEHR forum].

=== OpenAPI

The current schemas are not ready to be used as is on a OpenAPI definition of openEHR REST API. There is currently an experiment (demo) of this https://github.com/nedap/openehr-openapi[on a project to show how OpenAPI can work with openEHR].

== Alternative schemas

The https://github.com/openEHR/archie[Archie] json schemas alternative are autogenerated from BMM. The code to do so is available as part of Archie, at https://github.com/openEHR/archie/blob/master/tools/src/main/java/com/nedap/archie/json/JSONSchemaCreator.java[archie/JSONSchemaCreator.java]. It has the following benefits:

- can be used to validate, including all polymorphism except some generics
- tuned for speed of validation and quality of validation messages
- extensively tested against the Archie json mapping for the RM, even with additionalProperties: false set everywhere to test for completeness.
- the code to generate it is open source
- contains no extra information, so fast to parse.

It has the following drawbacks:

- not currently separated in packages or files, just one file, but the information to do so is present in the BMM models.
- nearly no documentation included, because the BMM files contain very little documentation.

An example of JSON Schema generated by Archie can be found https://gist.github.com/pieterbos/ff8a9c67fd3d346b423a8cd69befe67a[here].

== Acknowledgements

JSON schema were initially authored by https://www.code24.nl[Code24]. 

